services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitom_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    depends_on:
      app-seq:
        condition: service_started
        restart: true
      postgres_db:
        condition: service_started
        restart: true

  postgres_db:
    container_name: postgres_container
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=VitomDB
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  app-seq:
    image: datalust/seq:latest
    container_name: app-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8089:80

volumes:
  data:
