version: '3'

tasks:
  watch:
    dir: './src/API'
    cmds:
      - dotnet watch
  run:
    dir: './src/API'
    cmds:
      - dotnet run
  dropdb:
    dir: './src/Persistence'
    cmds:
      - dotnet ef database drop -f --startup-project ../API